// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-info-row-example-label'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'menu-enrich-metadata'
  | 'menu-import-bibliography'
  | 'pref-api-delay-label'
  | 'pref-auto-enrich-label'
  | 'pref-cail-key-description'
  | 'pref-cail-key-label'
  | 'pref-enrich-preisbn-label'
  | 'pref-help'
  | 'pref-llm-model-label'
  | 'pref-openrouter-key-description'
  | 'pref-openrouter-key-label'
  | 'pref-provider-label'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
