// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "openrouterApiKey": string;
      "autoEnrichOnImport": boolean;
      "llmModel": string;
      "enrichPreIsbn": boolean;
      "apiDelayMs": number;
    };
  }
}
